### ISSUE TITLE
[Feature Request] Add a random blinking animation when the dog is running in the Agility Scene

### ISSUE THREAD

**Issue by abdrdg** [abdrdg/Foundry#27]
# [Request] Dog randomly blinking while running in the Agility Scene
Description:
The request came from the Art team. They wanted the dog to look more natural and realistic by having a random blinking animation.
Here is the expected animation but the eye blinks on a random chance: 
![Anim-Recovered-JD (2)](https://github.com/abdrdg/Foundry/assets/53889966/85577aed-42e3-4865-85c8-e7c58dfdb9c7)

**Comment by johnzillakaiju** [comment]
need to wait for the sprites from the art team

**Comment by carebeardrew** [comment]
As per request from @abdrdg we shall close this now :D
