### ISSUE TITLE
[Emman][Visual] Obstacle course presents multiple color texture during agility mini game

### ISSUE THREAD

**Issue by emmanforce** [abdrdg/Foundry#37]
Description 
When the user opens the application and plays the agility mini-game, they will notice that a partial part of obstacle course presents several colors during the game. 
  
**Steps to Reproduce:**

1. Install and open prod-0.0.1.0-pre-release.apk in android device 

2. Tap the dog avatar 

3. Select the Agility mini-game in main menu 

4. Observe the different colors in obstacle course 

**Expected behavior:** 

The obstacle course is rendered properly without any issues 

 **Reproduced on:** 

 - Device: [Realme 5] 

 - Android Version: [10] 
 
 - Browser: N/A 

  - Version 0.0.1.0 

**Additional context:** 
 
When the user choose to return in main menu after failing or completing the agility mini-game, then re-entering the mini-game will fix the issue

**Attachments:**

https://github.com/abdrdg/Foundry/assets/135000859/6190bcb0-d81f-4942-ba03-2615e1019b51

**Comment by LexxTheSixth** [comment]
Issue does not occur on Dev build.

**Comment by emmanforce** [comment]
Issue **Fix Failed on dev-0.0.1.0-pre-release**, With same repro steps @LexxTheSixth 

**New behavior**
Half part of obstacle course does not present Several different textures. But a minimal part of obstacle course still shows different color texture.

**New attachment added:**

![image (13)](https://github.com/abdrdg/Foundry/assets/135000859/24ac06ef-31c0-49c4-b323-679987eabe4f)

**Comment by LexxTheSixth** [comment]
Issue does not occur on Dev 0.0.3 Pre-Release. Closing issue.
