### ISSUE TITLE
[Zhai] [Visual] The dog is presented at the back of the fence and in a higher position from the dog bowl during the feeding mini-game

### ISSUE THREAD

**Issue by zpaloma** [abdrdg/Foundry#38]
**Description**
When the user starts the feeding mini-game, it can be noticed that the dog is behind the fence background and in a higher position from the dog bowl. 
 
**Steps to Reproduced the behavior** 
1. Boot app on Foundry Build (1.0) 
2. Rotate the device into a landscape mode 
3. Tap the dog in the middle of the screen 
4. Tap the dog bowl icon to start the feeding mini-game
5. Observe the position of the dog 

**Expected Results**
The dog is presented in front of the fence and closer to the dog bowl. 

**Actual Results**
The dog is behind the fence background. 
 
**Smartphone**
-Tecno Spark 10pro
-Android 13 
-Google Chrome, Hi Browser 
-113.0.5672.162, v2.8.1.2 

**Attachment**
![(1)Dog_BehindFence](https://github.com/abdrdg/Foundry/assets/134998427/36fe85a8-b7f8-4c8d-92f8-859e6f9d24f8)

**Comment by LexxTheSixth** [comment]
Issue does not occur on Dev build.

**Comment by zpaloma** [comment]
@VeoWulfOfWallSt Issue no longer occurs on **Dev v0.0.1.0 Pre-Release**

**New behavior observed**
The dog avatar is now stationary in its position

**New attachment added**
![Screenshot_20230608-145022](https://github.com/abdrdg/Foundry/assets/134998427/8a9bf5a6-7579-4c9e-ba35-2ab150b2ec3d)

**Comment by cpulanco** [comment]
Issue no longer occurs on **Dev 0.0.1.1 Pre-Release**
