### ISSUE TITLE
[Zhai] [Functionality] The "Return to Main Menu" button does not go back to the main menu when tapped after finishing the feeding mini-game

### ISSUE THREAD

**Issue by zpaloma** [abdrdg/Foundry#39]
**Description**
When the user finishes the feeding mini-game, it can be noticed that the "Return to Main Menu" button does not go back to the main menu when tapped and it replays the game. 

**Steps to Reproduced the behavior**
1. Boot app on Foundry Build (1.0) 
2. Rotate the device into a landscape mode 
3. Tap the dog in the middle of the screen 
4. Tap the dog bowl icon to start the feeding mini-game 
5. Finish the mini-game 
6. Tap the “Return to Main Menu” button 

**Expected Results**
Tapping the “Return to Main Menu” button lets the screen go back to the main menu screen. 

**Actual Results**
The "Return to Main Menu" button does not go back to the main menu. 
 
**Smartphone**
-Tecno Spark 10pro 
-Android 13 
-Google Chrome, Hi Browser 
-113.0.5672.162, v2.8.1.2 

**Attachment**
https://github.com/abdrdg/Foundry/assets/134998427/0f637ecc-55e3-48cc-82b0-2f1c530677fc

**Comment by LexxTheSixth** [comment]
Issue does not occur on Dev build.

**Comment by zpaloma** [comment]
@Syoraka Issue is Fix Verified on **Dev v0.0.1.0 Pre-Release**

**Comment by cpulanco** [comment]
Issue is Fix Verified on **Dev 0.0.1.1 Pre-Release** Closing Issue
