### ISSUE TITLE
[Zhai] [Visual] The food is falling behind the fence background during the feeding mini-game

### ISSUE THREAD

**Issue by zpaloma** [abdrdg/Foundry#40]
**Description**
When the user starts the feeding mini-game, it can be noticed that the foods are falling behind the fence background.
 
**Steps to Reproduced the behavior**
1. Boot app on Foundry Build (1.0) 
2. Rotate the device into a landscape mode 
3. Tap the dog in the middle of the screen 
4. Tap the dog bowl icon to start the feeding mini-game 
5. Observe the falling foods 

**Expected Results**
Foods are falling in front of the fence without any issues.

**Actual Results**
The food falls behind the fence. 

**Smartphone**
-Tecno Spark 10pro 
-Android 13 
-Google Chrome, Hi Browser 
-113.0.5672.162, v2.8.1.2

**Attachment**
https://github.com/abdrdg/Foundry/assets/134998427/70bef9ef-689a-4fbe-9da4-0428d4a4e7b4

**Comment by LexxTheSixth** [comment]
Issue does not occur on Dev build.

**Comment by zpaloma** [comment]
@khmflrdlz Issue is Fix Verified on **Dev v0.0.1.0 Pre-Release**

**Comment by cpulanco** [comment]
Fix Verified on **Dev 0.0.1.1 Pre-Release** Closing issue.
