### ISSUE TITLE
[Zhai] [Functionality] The dog can be controlled separately from the dog bowl during the feeding mini-game

### ISSUE THREAD

**Issue by zpaloma** [abdrdg/Foundry#41]
**Description**
When the user starts the feeding mini-game and swipes the dog left and right, it can be noticed that the dog can be controlled separately from the dog bowl. 

**Steps to Reproduced the behavior**
1. Boot app on Foundry Build (1.0) 
2. Rotate the device into a landscape mode 
3. Tap the dog in the middle of the screen 
4. Tap the dog bowl icon to start the feeding mini-game 
5. Swipe the dog left and right 

**Expected Results**
The dog and dog bowl are controlled as one unit. 

**Actual Results**
The dog can be controlled separately. 
 
**Smartphone**
-Tecno Spark 10pro 
-Android 13 
-Google Chrome, Hi Browser 
-113.0.5672.162, v2.8.1.2 

**Attachments**
https://github.com/abdrdg/Foundry/assets/134998427/87ee0312-e2f3-4116-b46d-879e83373594

**Comment by LexxTheSixth** [comment]
Issue does not occur on Dev build.

**Comment by zpaloma** [comment]
@carebeardrew Issue no longer occurs on **Dev v0.0.1.0 Pre-Release**

**Comment by cpulanco** [comment]
Issue no longer occurs on **Dev 0.0.1.1 Pre-Release**
