### ISSUE TITLE
[Zhai] [Functionality] The dog and dog bowl can be controlled after finishing the feeding mini-game

### ISSUE THREAD

**Issue by zpaloma** [abdrdg/Foundry#42]
**Description**
When the user finishes the feeding mini-game, it can be noticed that the "Return to Main Menu" button does not go back to the main menu when tapped and it replays the game. 

**Steps to Reproduced the behavior**
1. Boot app on Foundry Build (1.0)
2. Rotate the device into a landscape mode 
3. Tap the dog in the middle of the screen 
4. Tap the dog bowl icon to start the feeding mini-game 
5. Finish the mini-game 
6. Swipe the dog and food bowl left and right

**Expected Results**
Users are unable to control the dog and food bowl after finishing the mini-game. 

**Actual Results**
The dog and dog bowl can still be controlled. 

**Smartphone**
-Tecno Spark 10pro 
-Android 13 
-Google Chrome, Hi Browser 
-113.0.5672.162, v2.8.1.2 

**Attachments**
https://github.com/abdrdg/Foundry/assets/134998427/34043aad-3130-4366-96dd-30256bb5cca0

**Comment by CM-GARO** [comment]
asdasd

**Comment by LexxTheSixth** [comment]
Issue does not occur on Dev build.

**Comment by zpaloma** [comment]
@LexxTheSixth Issue is Fix Failed on **Dev v0.0.1.0 Pre-Release**

**New behavior observed**
The dog avatar is now stationary in its position, however, the dog bowl can still be controlled after finishing the mini-game.

**New attachment added**

https://github.com/abdrdg/Foundry/assets/134998427/b02513d5-19ad-45d1-a18f-bdc17dd9996e

**Comment by cpulanco** [comment]
Fix Verified on **Dev 0.0.1.1 Pre-Release** Closing Issue
