### ISSUE TITLE
[Bret][Visual][Dev] The falling food are disappearing mid-air before landing in the food bowl in Feeding mini-game.

### ISSUE THREAD

**Issue by brodriguez-hub** [abdrdg/Foundry#46]
When the user enters the Feeding minigame, the food is disappearing before it lands in the dog's food bowl in the mini-game.

Steps: 
1. Launch the application 
2. The application will open. 
3. Tap the Dog in the middle of the screen. 
4. Tap the food bowl. 
5. You will enter the minigame.
6. Observe the falling food landing in the bowl.

Expected Result: The food will reach the food bowl before it disappears.
Actual Results: The food disappear in mid-air before it lands in the food bowl.

Devices:
-Realme Pro 3
-Android 11
-FW 11.4

Please note that the visual issue of falling foods is noticeable while playing the Feeding mini-game.

https://github.com/abdrdg/Foundry/assets/135010750/aa6791ae-375b-4e6b-8a27-9ff19ebd66ac

**Comment by khmflrdlz** [comment]
Issue still occurs in **Dev 0.0.1.1 Pre-Release**

**Comment by LexxTheSixth** [comment]
Issue does not occur on **Dev 0.0.3 Pre-Release**. Closing issue.
