### ISSUE TITLE
[Emman][Visual] Multiple assets are not visible when playing in landscape mode during feeding mini-game

### ISSUE THREAD

**Issue by emmanforce** [abdrdg/Foundry#63]
**Describe the bug**
When the user is about to play the feeding mini game in landscape mode, they will notice that the assets are not visible and a blue texture is present. Rotating the phone in landscape mode assets are visible but seem not functional 

**To Reproduce**
1. Download and install (dev-0.0.2.0-pre-release.apk)
2. Switch Android phone in Landscape
3. Tap the dog icon in main-menu
4. Select Feeding mini-game
5. Observe the mini-game in 
6. Rotate in Portrait mode

**Expected behavior**
Mini-games are stable and accessible in all orientation

Actual Behavior 
Assets are missing in feeding when playing in landscape orientation

**Smartphone :**
 - Device: Device: Redmi 5 
 - OS: Android Version: 10
 - Browser [N/A]
 - Version [dev-0.0.2.0-pre-release.apk]

**Additional context**
N/A

https://github.com/abdrdg/Foundry/assets/135000859/484f8c1a-af5c-45f0-ac39-d66877e02700

**Comment by LexxTheSixth** [comment]
Issue does not occur on Dev 0.0.3 Pre-Release. Closing issue.
