### ISSUE TITLE
[Mark] [Visual] [The food asset is not removed on screen when finishing the Feeding Mini game]

### ISSUE THREAD

**Issue by CM-GARO** [abdrdg/Foundry#66]
**Description:** 

When the user plays the Feeding mini game it can be noticed that the food prefab is still present in the game over screen

**To Reproduce** 

1. Download and install Dev 0.0.2.0 Pre-Release 
2. Set phone orientation in landscape 
3. Start the application 
4. Tap on the dog 
5. Select the feeding mini game 
6. Wait for the game to finish 

**Actual behavior** 

The assets for the food are present at the game over screen 

**Expected behavior** 

The food assets are removed from the screen 

**Reproduced on** 

- Device: Redmi 7 
- OS: Android 9 
- Browser: N/A 
- Version Dev 0.0.2.0 Pre-Release 

**Additional context** 

Please see attachment 

**Screenshots** 

![Image](https://github.com/abdrdg/Foundry/assets/132534398/64334c43-5937-4253-a750-8914b7e23239)

**Comment by carebeardrew** [comment]
Fix Added should be available next build

**Comment by CM-GARO** [comment]
Issue no longer occurs on Dev 0.0.3.0 Pre-Release
