### ISSUE TITLE
[Mark] [Visual] [Heart icon overlaps with “Lives” text in Agility mini game]

### ISSUE THREAD

**Issue by CM-GARO** [abdrdg/Foundry#75]
**Description:** 

When the user enters the agility minigame, it can be noticed that the life counter covers up a portion of the text above 

**To Reproduce** 

1. Download and install Dev 0.0.3.0 Pre-Release 
2. Start the application 
3. Tap the dog 
4. Select the agility mini game 

**Actual behavior** 

The heart asset for the dog is covering the lives indicator text 

**Expected behavior** 

The text is not covered and is seen clearly 

**Reproduced on** 

- Device: Redmi 7 
- OS: Android 9 
- Browser: N/A 
- Version Dev 0.0.3.0 Pre-Release 

**Additional context** 

Please see attachment 

**Screenshots** 

![Image](https://github.com/abdrdg/Foundry/assets/132534398/5621b651-a2c7-497b-812e-c718db9e4888)

**Comment by VeoWulfOfWallSt** [comment]
Issue fixed
