### ISSUE TITLE
[Mark] [Visual] [The left side of the fence does not extend fully in the Feeding mini game]

### ISSUE THREAD

**Issue by CM-GARO** [abdrdg/Foundry#76]
**Description:** 

When the user enters the feeding mini-game, it can be noticed that one side of the fence has a little bit of gap 

**To Reproduce** 

1. Download and install Dev 0.0.3.0 Pre-Release 
2. Start the application 
3. Tap the dog 
4. Select the feeding mini game 

**Actual behavior** 

The leftmost part of the fence has a gap 

**Expected behavior** 

The fence extends fully to the end of the screen 

Reproduced on 

- Device: Redmi 7 
- OS: Android 9 
- Browser: N/A 
- Version Dev 0.0.3.0 Pre-Release 

**Additional context** 

Please see attachment 

**Screenshots** 

![Image](https://github.com/abdrdg/Foundry/assets/132534398/531f2ab7-1a8a-4a4a-8656-b0e83dcc2003)

**Comment by VeoWulfOfWallSt** [comment]
Should be fixed in the next build
