### ISSUE TITLE
[Bret][Functionality][dev]The dog bowl is not interactable after 2 taps on the Screen

### ISSUE THREAD

**Issue by brodriguez-hub** [abdrdg/Foundry#78]
When the user taps the screen twice while in mini-game Feeding it makes the dog bowl an interactable and loses its function to move.

1. Launch the application
2. Tap any dog in Main Menu
3. Select Feeding mini-game
4. Play the game
5. Tap the screen twice.
6. Swipe the dog bowl again
7. Observe the dog bowl issue.

**Expected behavior**
The dog bowl is still interactable after tapping the screen twice.

*Screenshots*
https://github.com/abdrdg/Foundry/assets/135010750/867f8926-cafb-463a-a765-863b42854199

 - Device: Realme 3 Pro
 - OS: Android 11
 - FW: 11.3

Please note that this issue may interrupt the user overall experience.

**Comment by LexxTheSixth** [comment]
Not an issue, multi-touch is deactivated for the game. Closing issue.
